#pragma once

#include <cstddef>

namespace rover::hal
{

struct EmbeddedAsset
{
    const char *file_name;
    const unsigned char *start;
    const unsigned char *end;
};

}  // namespace rover::hal

/**
 * Do not edit - the rest of this file is auto-generated by CMakeLists.txt.
 *
 * Aut-generation means that the `esp32` folder is agnostic to new asset
 * files being added in the application layer. If that becomes too complicated,
 * go back to hardcoding this file, using build/esp32/assets_esp32.h as a guide.
 * See CMakeLists.txt for strategies to debug missing asset files.
 */

/* <----- EXTERN DECLARATION BLOCK -----> */

namespace rover::hal
{
inline constexpr EmbeddedAsset embedded_assets[] = {
    /* <------ EMBEDDED ASSETS BLOCK -----> */
};

inline constexpr std::size_t embedded_asset_count =
    sizeof(embedded_assets) / sizeof(embedded_assets[0]);
}  // namespace rover::hal