#pragma once

#include <cstddef>

/**
 * Do not edit - this code is auto-generated by CMakeLists.txt.
 *
 * Auto-generation means that the `esp32` folder is agnostic to new asset
 * files being added in the application layer. If that becomes too complicated,
 * go back to hardcoding this file, using build/esp32/assets_esp32.h as a guide.
 * See CMakeLists.txt for strategies to debug missing asset files.
 */

// <----- BEGIN EXTERN DECLARATION BLOCK ----->
extern const unsigned char _binary_drivetrain_omni_control_js_start[];
extern const unsigned char _binary_drivetrain_omni_control_js_end[];
extern const unsigned char _binary_led_control_js_start[];
extern const unsigned char _binary_led_control_js_end[];
extern const unsigned char _binary_motor_control_js_start[];
extern const unsigned char _binary_motor_control_js_end[];
extern const unsigned char _binary_pwm_control_js_start[];
extern const unsigned char _binary_pwm_control_js_end[];
extern const unsigned char _binary_styles_css_start[];
extern const unsigned char _binary_styles_css_end[];
// <----- END EXTERN DECLARATION BLOCK ----->

namespace rover::hal
{

struct EmbeddedAsset
{
    const char *file_name;
    const unsigned char *start;
    const unsigned char *end;
};

inline constexpr EmbeddedAsset embedded_assets[] = {
    // <----- BEGIN EMBEDDED ASSETS BLOCK ----->
    {"drivetrain_omni_control.js", _binary_drivetrain_omni_control_js_start,
     _binary_drivetrain_omni_control_js_end},
    {"led_control.js", _binary_led_control_js_start, _binary_led_control_js_end},
    {"motor_control.js", _binary_motor_control_js_start, _binary_motor_control_js_end},
    {"pwm_control.js", _binary_pwm_control_js_start, _binary_pwm_control_js_end},
    {"styles.css", _binary_styles_css_start, _binary_styles_css_end},
    // <----- END EMBEDDED ASSETS BLOCK ----->
};

inline constexpr std::size_t embedded_asset_count =
    sizeof(embedded_assets) / sizeof(embedded_assets[0]);

}  // namespace rover::hal
